#!/usr/bin/env ruby

# frozen_string_literal: true

# SPOTIFY_API - TOKEN - https://developer.spotify.com/console/get-playlist-tracks/?playlist_id=37i9dQZEVXbMXbN3EUUhlg
# GOOGLE_API  - TOKEN - https://console.developers.google.com/apis/library/youtube.googleapis.com

require 'uri'
require 'net/http'
require 'spotify-client'
require 'task_progress_bar'
require_relative 'src/spotify_downloader'

config = {
  download_path: '~/Music/',
  spotify_token: 'SPOTIFY-TOKEN',
  google_token:  'YOUTUBE-TOKEN'
}

client = SpotifyDownloader.new(config)
client.download!('PLAYLIST-ID')
